//! SlateDuck Catalog: DuckLake catalog operations backed by SlateDB.

pub mod audit;
pub mod cache;
pub mod cdc;
pub mod checkpoint;
pub mod cleanup;
pub mod corpus;
pub mod cost;
pub mod encryption;
pub mod error;
pub mod excise;
pub mod export;
pub mod gc;
pub mod init;
pub mod inspect;
pub mod metrics;
pub mod migrate;
pub mod partition;
pub mod performance;
pub mod reader;
pub mod repair;
pub mod store;
pub mod streaming;
pub mod verify;
pub mod warmup;
pub mod writer;

pub use audit::{AuditChange, AuditEntry};
pub use cache::{cache_utilization, CacheStats};
pub use cdc::{CdcChangeKind, CdcEvent, CdcSnapshot, CdcTailer, WebhookPayload};
pub use corpus::{corpus_diff, corpus_validate, parse_corpus, CorpusRecord, ValidateResult};
pub use cost::{tune_for_cost_target, ApiCostReport, CostMode};
pub use encryption::{EncryptionConfig, EncryptionError};
pub use error::{CatalogError, CatalogResult};
pub use metrics::CatalogMetrics;
pub use migrate::{migrate_apply, migrate_dry_run, MigrateDryRunResult, MigrateResult};
pub use partition::{CatalogRegistry, DatasetEntry, PartitionedWriter};
pub use performance::{BenchmarkReport, HotKeyState, SlateDbTuning};
pub use reader::{CatalogReader, SnapshotDiff};
pub use store::{CatalogStore, OpenOptions};
pub use streaming::{measure_ingest_throughput, IngestRecord, IngestResult, SlateDuckSink};
pub use warmup::{publish_writer_endpoint, read_writer_endpoint, warmup_cache, WarmupResult};
pub use writer::{CatalogWriter, validate_app_metadata_key};
